// sc-mobile - Native mobile bindings for iOS and Android
// This crate exports the Iron Core API via UniFFI

// Re-export all types from sc-core for UniFFI
// The scaffolding is generated by sc-core's build.rs
pub use sc_core::*;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mobile_bindings_lifecycle() {
        let core = IronCore::new();
        assert!(!core.is_running());

        core.start().expect("Failed to start");
        assert!(core.is_running());

        let reading = EnvironmentalReading {
            battery_level: 0.9,
            network_type: NetworkType::Wifi,
        };

        core.set_environmental_reading(reading);
        let report = core.get_vitality_report();

        assert!(matches!(report.state, NodeState::Hub));
        core.stop();
        assert!(!core.is_running());
    }

    #[test]
    fn test_mobile_mesh_parameters() {
        let core = IronCore::new();
        core.start().unwrap();

        let params = core.get_mesh_parameters();
        assert!(params.mesh_n > 0);
        assert!(params.mesh_n_low <= params.mesh_n);
        assert!(params.mesh_n <= params.mesh_n_high);

        core.stop();
    }

    #[test]
    fn test_mobile_identity() {
        let core = IronCore::new();

        let info_before = core.get_identity_info();
        assert!(!info_before.initialized);

        core.initialize_identity().expect("Failed to initialize identity");

        let info_after = core.get_identity_info();
        assert!(info_after.initialized);
        assert!(info_after.identity_id.is_some());
        assert!(info_after.public_key_hex.is_some());
    }

    #[test]
    fn test_mobile_delegation() {
        let core = IronCore::new();

        let status_before = core.get_delegation_status();
        assert!(!status_before.is_active);
        assert_eq!(status_before.delegate_count, 0);

        // Try to enable delegation (will fail without peers, but tests the API)
        let result = core.enable_delegated_listening("test_token".to_string());
        assert!(result.is_err()); // Expected - no delegates available
    }
}
