# SwiftLint Configuration for Sovereign Communications

# Disabled rules (customize as needed)
disabled_rules:
  - trailing_whitespace
  - line_length
  - todo

# Opt-in rules (additional checks)
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional

# Rule configurations
line_length:
  warning: 150
  error: 200

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

# Paths to include/exclude
included:
  - SovereignCommunications

excluded:
  - Pods
  - .build
  - build
  - DerivedData

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"
